# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://wowchemy.com/docs/guide/language/

# Default language
zh:
  languageCode: zh-Hans
  languageName: 中文
  title: 林德旸
  weight: 1
  menu:
    main:
      - name: 主页
        url: '#about'
        weight: 10
      - name: 项目
        url: '#projects'
        weight: 20
      - name: 经历
        url: '#experience'
        weight: 40

en:
  languageCode: en-us
  languageName: English
  title: Deyang Lin
  weight: 2
  menu:
    main:
      - name: Home
        url: '#about'
        weight: 10
      - name: Projects
        url: '#projects'
        weight: 20
      - name: Experience
        url: '#experience'
        weight: 40
